Algoritmo "bglh doido"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 2/25/2021
Var
// Seção de Declarações das variáveis 
nome: caracter
n1,n2,n3,n4,media: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
nome<- "yuri"
escreva ("nome do aluno: ")
escreval (nome)
n1<- 8
n2<- 7
n3<- 6
n4<- 7
media<- (n1+n2+n3+n4)/4
escreva ("media: ")
escreval (media)
se media <= 7 entao
escreva ("o aluno esta reprovado")
senao
escreva ("o aluno esta aprovado")
fimse


Fimalgoritmo