Algoritmo "declarações"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 3/9/2021
Var
// Seção de Declarações das variáveis 
NB: caractere
NA: real
NMAT: inteiro
SX: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo