Algoritmo "função"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 3/9/2021
Var
// Seção de Declarações das variáveis 
x,y: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("entre com valor de X:")
leia (X)
y<- 3*x+2
escreva ("y=")
escreva (y)

Fimalgoritmo