Algoritmo "Gasolina"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 3/9/2021
Var
// Seção de Declarações das variáveis 
consumo, volume, distancia: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("qual a distancia percorrida?")
leia (distancia)
escreva ("qual o volume de gasolina?")
leia (volume)
consumo<- distancia/volume
escreva ("o consumo medio foi de")
escreva (consumo)
escreva ("l")
Fimalgoritmo