Algoritmo "intervalo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 3/22/2021
Var
// Seção de Declarações das variáveis 
n:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
n<-1
enquanto (n<100) faca
escreva(n)
n<-n+1
fimenquanto

Fimalgoritmo