Algoritmo "preços"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 3/9/2021
Var
// Seção de Declarações das variáveis 
cor: caractere


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("qual cor?")
leia(cor)
se cor="verde" entao
escreva ("preço=r$10,00")
fimse
se cor="azul" entao
escreva ("preço=r$20,00")
fimse
se cor="amarelo" entao
escreva ("preço=r$30,00")
fimse
se cor="vermelho" entao
escreva ("preço=r$40,00")
fimse
Fimalgoritmo